CREATE DATABASE SPMED_MARCAUM
GO

USE SPMED_MARCAUM;
GO

--SITUACAO
CREATE TABLE Situacao(
	IdSituacao TINYINT PRIMARY KEY IDENTITY,
	Descricao VARCHAR(15)
);
GO

--TIPO DE USUARIO
CREATE TABLE TipoUsuario(
	IdTipoUsuario TINYINT PRIMARY KEY IDENTITY,
	TituloTipoUsuario VARCHAR(20)
);
GO

--USUARIO
CREATE TABLE Usuario(
	IdUsuario INT PRIMARY KEY IDENTITY,
	IdTipoUsuario TINYINT FOREIGN KEY REFERENCES TipoUsuario(IdTipoUsuario),
	NomeUsuario VARCHAR(20),
	Email VARCHAR(256),
	Senha VARCHAR(9)
);
GO

--PACIENTE
CREATE TABLE Paciente(
	IdPaciente INT PRIMARY KEY IDENTITY,
	IdUsuario INT FOREIGN KEY REFERENCES Usuario(IdUsuario),
	Telefone VARCHAR(14),
	DataNascimento DATE,
	Endereco VARCHAR(150),
	Rg VARCHAR(12),
	Cpf VARCHAR(14)
);
GO

--CLINICA
CREATE TABLE Clinica(
	IdClinica SMALLINT PRIMARY KEY IDENTITY,
	NomeFantasia VARCHAR(20),
	RazaoSocial VARCHAR(50),
	Endereco VARCHAR(150),
	Cnpj VARCHAR(18),
	HorarioAbertura TIME,
	HorarioFechamento TIME
);
GO

--ESPECIALIDADE
CREATE TABLE Especialidade(
	IdEspecialidade SMALLINT PRIMARY KEY IDENTITY,
	Descricao VARCHAR(35)
);
GO

--MEDICO
CREATE TABLE Medico(
	IdMedico INT PRIMARY KEY IDENTITY,
	IdUsuario INT FOREIGN KEY REFERENCES Usuario(IdUsuario),
	IdClinica SMALLINT FOREIGN KEY REFERENCES Clinica(IdClinica),
	IdEspecialidade SMALLINT FOREIGN KEY REFERENCES Especialidade(IdEspecialidade),
	Crmv VARCHAR(8)
);
GO

--CONSULTA
CREATE TABLE Consulta(
	IdConsulta INT PRIMARY KEY IDENTITY,
	IdMedico INT FOREIGN KEY REFERENCES Medico(IdMedico),
	IdPaciente INT FOREIGN KEY REFERENCES Paciente(IdPaciente),
	IdSituacao TINYINT FOREIGN KEY REFERENCES Situacao(IdSituacao),
);
GO